name: concoin
description: A flutter coin flipping app for sore losers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  circular_countdown_timer: ^0.2.0
  toggle_switch: ^1.4.0
  razorpay_flutter: ^1.2.9
  sizer: ^2.0.15
  font_awesome_flutter: ^9.2.0
  animated_widgets: ^1.1.0
  page_transition: ^2.0.4
  http: ^0.13.0
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.17
  pinput: ^1.2.2
  dotted_border: ^2.0.0+2
  image_picker_gallery_camera: ^0.2.2
  connectivity: ^3.0.6
  flutter_local_notifications: ^9.0.0
  path_provider: ^2.0.2
  firebase_messaging: ^10.0.4
  permission_handler: ^8.3.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.3
  image_cropper: ^1.4.1
  http_parser: ^4.0.0
  location: ^4.3.0
  geocoder: ^0.2.1
  cached_network_image: ^3.2.0
  loading_animation_widget: ^1.2.0+4
  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3



flutter_native_splash:
  color: "#2196f3"
  image: assets/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf
